# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: influxdb
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: influxdb
  type: influxdb
  access: proxy
  database: hep
  url: http://influxdb:8086
  editable: true
  jsonData:
    timeInterval: "15s"
- name: loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true
